name: CI

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Pushing new changes to a branch will cancel any in-progress CI runs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # reduces noise from npm post-install scripts
  DISABLE_OPENCOLLECTIVE: true
  OPEN_SOURCE_CONTRIBUTOR: true
  NPM_CONFIG_AUDIT: false
  NPM_CONFIG_FUND: false

# Restrict jobs in this workflow to have no permissions by default; permissions
# should be granted per job as needed using a dedicated `permissions` block
permissions: {}

jobs:
  reproduce:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm ci
      - run: npm run typescript
